In [ ]:
from onpolicy.envs.aps.aps import Aps
from types import SimpleNamespace

import yaml
import argparse
import numpy as np

yaml_path = "/home/mzi/aps-infomarl/onpolicy/aps-config.yaml"
with open(yaml_path, 'r') as file:
    yaml_config = yaml.safe_load(file)
yaml_config


def dict_to_object(d):
    if isinstance(d, dict):
        return SimpleNamespace(**{k: dict_to_object(v) for k, v in d.items()})
    return d
obj = dict_to_object(yaml_config)
env = Aps(obj.env_args)


In [20]:
obs, state, mask, info, same_ue, same_ap = env.reset()


In [25]:
random_binary_array = np.random.randint(2, size=80)

obs, state, reward, done, info, mask, same_ue, same_ap = env.step(random_binary_array)

In [1]:
import torch

In [11]:
print(a)

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])


In [27]:
import torch

# Create a tensor of size 10 (from 0 to 9)
tensor = torch.arange(10)
print(tensor)

# Repeat the tensor (2, 3) times
repeated_tensor = tensor.repeat(2, 3, 1)
print(repeated_tensor)

print(repeated_tensor.reshape((-1, 10)))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [28]:
a = torch.arange(60).reshape(2, 3, 10)

print(a.reshape((-1, 10)))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])
